# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site
title: raceto11
email: raceto11blog@gmail.com.com
description: >- # this means to ignore newlines until "baseurl:"
  The Cue Sports Blog.
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/poolblog" # the subpath of your site, e.g. /blog
url: "https://s2moore.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: raceto11blog
# github_username:  raceto11
#logo: 'assets/images/logo.png'
#favicon: 'assets/images/favicon.ico'
#disqus: 'demowebsite'
email: 'raceto11blog@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'


# Fields minima uses but not defaulted with the jekyll new command.
# Author is the default for posts, the Atom feed and is used in the footer.
author: admin@raceto11
facebook_username: raceto11
# Add a copyright and copyright symbol.  Year automatically updated.
copyright: "raceto11"
# title-logo is a new field that, when used, displays a logo instead of custom text.
# Ideally, image is 50px high and takes up minimal horizontal space.
# title-logo: /assets/images/my-logo.png (or JPG etc)
# title-logo: /assets/images/logo-raceto11.png

# Build settings
# Removed minima theme as it now a regular theme
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


